//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
