//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAttachment
    {
        public long ID { get; set; }
        public long TicketNo { get; set; }
        public byte[] Attachment { get; set; }
        public string fileName { get; set; }
        public string fileType { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
