//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.StatusHistories = new HashSet<StatusHistory>();
            this.TicketAttachments = new HashSet<TicketAttachment>();
        }
    
        public long TicketNo { get; set; }
        public int CategoryID { get; set; }
        public string Subject { get; set; }
        public string Details { get; set; }
        public string Priority { get; set; }
        public string Impact { get; set; }
        public int Issuer { get; set; }
        public string Status { get; set; }
        public int SiteNo { get; set; }
        public string Assignee { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ActivePhone { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Site Site { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual ICollection<StatusHistory> StatusHistories { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
    }
}
