//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.StatusHistories = new HashSet<StatusHistory>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string userName { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public Nullable<int> deptID { get; set; }
    
        public virtual ICollection<StatusHistory> StatusHistories { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual Department Department { get; set; }
    }
}
